-- Create the artifacts storage bucket for baseline outputs, benchmark results,
-- validation logs, agent traces, patch diffs, and proposal evidence bundles.
-- Only the backend service role uploads artifacts.
-- Users retrieve artifacts via signed URLs generated by FastAPI.
insert into storage.buckets (id, name, public)
values ('artifacts', 'artifacts', false);
