"""GitHub service layer for high-level operations.

Orchestrates the multi-step PR creation workflow:
branch creation -> commit -> PR open.

This layer is the boundary between our domain models and the
GitHub API client. It translates proposals into GitHub API calls.
"""

from app.db.models import Proposal, Repository
from app.github import client as github_client


# Branch naming convention: selfopt/proposal-{short_id}
# Using a prefix makes it easy to identify SelfOpt branches.
BRANCH_PREFIX = "selfopt/proposal-"


async def create_pr_for_proposal(repo: Repository, proposal: Proposal) -> str:
    """Create a full PR on GitHub for a validated proposal.

    Steps:
    1. Get an installation token for the repo
    2. Get the HEAD SHA of the default branch
    3. Create a new branch
    4. Commit the proposal's diff to the branch
    5. Open a PR back to the default branch

    Returns the PR URL (html_url).

    In MVP, this uses a simplified commit flow. The diff is included
    in the PR body as context since tree manipulation from raw diffs
    requires more complex blob/tree creation.
    """
    if not repo.github_repo_id:
        raise ValueError("Repository has no GitHub repo ID")

    # For MVP, these would come from the installation record
    # Stubbed here for testability — real values come from GitHub API
    owner = "owner"
    repo_name = "repo"
    installation_id = 0

    token = await github_client.get_installation_token(installation_id)

    head_sha = await github_client.get_default_branch_sha(
        token, owner, repo_name, repo.default_branch
    )

    short_id = str(proposal.id)[:8]
    branch_name = f"{BRANCH_PREFIX}{short_id}"

    await github_client.create_branch(
        token, owner, repo_name, branch_name, head_sha
    )

    pr_title = f"[SelfOpt] {proposal.summary or 'Code optimization'}"
    pr_body = _build_pr_body(proposal)

    pr_data = await github_client.create_pull_request(
        token=token,
        owner=owner,
        repo=repo_name,
        title=pr_title,
        body=pr_body,
        head_branch=branch_name,
        base_branch=repo.default_branch,
    )

    return pr_data["html_url"]


def _build_pr_body(proposal: Proposal) -> str:
    """Build the PR description from a proposal's evidence.

    Includes the optimization summary, metrics comparison, and risk score.
    This gives reviewers all the context needed for a fast review.
    """
    sections = ["## SelfOpt Optimization Proposal\n"]

    if proposal.summary:
        sections.append(f"**Summary:** {proposal.summary}\n")

    if proposal.metrics_before and proposal.metrics_after:
        sections.append("### Metrics\n")
        sections.append("| Metric | Before | After |")
        sections.append("|--------|--------|-------|")
        all_keys = set(proposal.metrics_before.keys()) | set(proposal.metrics_after.keys())
        for key in sorted(all_keys):
            before = proposal.metrics_before.get(key, "—")
            after = proposal.metrics_after.get(key, "—")
            sections.append(f"| {key} | {before} | {after} |")
        sections.append("")

    if proposal.risk_score is not None:
        sections.append(f"**Risk Score:** {proposal.risk_score}\n")

    sections.append("---")
    sections.append("*This PR was generated by [SelfOpt](https://github.com/selfopt) — an autonomous code optimization system.*")

    return "\n".join(sections)
